export const GlobalState = {
  levels: [],
  studyPlans: [],
  degrees: [],
  students: [],
  teachers: [],
  roles: [],
  pursuetypes: [],
  shifts: [],
  testtypes: [],
  users: [],
  userLogin: {},
  loading: false,
  error: false,
  message: "",
  portalTime: null,
};
